version: '3'
services:
  ngrinder-controller:
    image: ngrinder/controller
    container_name: ngrinder-traffic-bank
    ports:
      - "1080:80" # 웹페이지, Id: admin, password: admin
      - "16001:16001"
      - "12000-12009:12000-12009"
  ngrinder-agent:
    image: ngrinder/agent
    container_name: agent-traffic-bank
    entrypoint: [ "/scripts/run.sh", "ngrinder-controller:80" ]
    links:
      - ngrinder-controller