server:
  port: 0 # random port? ??

spring:
  application:
    name: product-service
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # eureka? random port? ?? ??? ?? ??? ??
  client:
    register-with-eureka: true
    fetch-registry: true # eureka-server?? instance ??? ????? ????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


