version: '3'

services:
  mysql:
    container_name: "mysql"
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    volumes:
      - ./db/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 16379:6379
    volumes:
      - ./db/redis:/data
    command: redis-server --port 6379 --requirepass 1234
