server:
  port: 9001
spring:
  application:
    name: userService
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # eureka-server?? instance ??? ????? ????
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
